import { sql } from "@/lib/db";
import type { SiteAssessment } from "./types";

const RECENT_ARTICLE_LOOKBACK = 5;
const FRESH_ASSET_LIMIT = 50;

/**
 * Inspect the site's current state to inform strategy selection.
 *
 * Reads from v2 tables only (no fallback to legacy). Strategies score
 * themselves against this snapshot.
 */
export async function assessSite(siteId: string): Promise<SiteAssessment> {
  // Pillar coverage across ALL v2 articles (drafts included). Drafts
  // occupy pillar slots in the portfolio just like published rows, so
  // pillar-fill targets the gap based on what exists, not what's live.
  const pillarRows = await sql`
    SELECT unnest(content_pillars) AS pillar, COUNT(*)::int AS n
    FROM blog_posts_v2
    WHERE site_id = ${siteId}
      AND status NOT IN ('archived', 'flagged')
    GROUP BY pillar
  `;
  const pillarCoverage: Record<string, number> = {};
  for (const r of pillarRows) {
    pillarCoverage[r.pillar as string] = r.n as number;
  }

  // Recent article pillars — last N v2 articles' first pillar (any status
  // except archived/flagged). Strategies use this to avoid back-to-back
  // repetition during a batch run.
  const recentRows = await sql`
    SELECT content_pillars
    FROM blog_posts_v2
    WHERE site_id = ${siteId}
      AND status NOT IN ('archived', 'flagged')
    ORDER BY created_at DESC
    LIMIT ${RECENT_ARTICLE_LOOKBACK}
  `;
  const recentArticlePillars = recentRows
    .map((r) => (Array.isArray(r.content_pillars) && r.content_pillars.length > 0
      ? (r.content_pillars[0] as string)
      : null))
    .filter((p): p is string => p !== null);

  const [count] = await sql`
    SELECT COUNT(*)::int AS n FROM blog_posts_v2 WHERE site_id = ${siteId}
  `;
  const publishedCount = (count?.n as number) || 0;

  // Fresh + high-quality assets, excluding any already used as v2 seed
  // (seed_asset_id) or hero (hero_asset_id) on a v2 article.
  const usedRows = await sql`
    SELECT DISTINCT id FROM (
      SELECT seed_asset_id AS id FROM blog_posts_v2 WHERE site_id = ${siteId} AND seed_asset_id IS NOT NULL
      UNION
      SELECT hero_asset_id AS id FROM blog_posts_v2 WHERE site_id = ${siteId}
    ) u
  `;
  const usedIds = new Set(usedRows.map((r) => r.id as string));

  const candidateRows = await sql`
    SELECT id
    FROM media_assets
    WHERE site_id = ${siteId}
      AND media_type ILIKE 'image%'
      AND triage_status NOT IN ('quarantined', 'shelved')
      AND status NOT IN ('deleted', 'failed')
      AND context_note IS NOT NULL
    ORDER BY quality_score DESC NULLS LAST, created_at DESC
    LIMIT ${FRESH_ASSET_LIMIT * 3}
  `;
  const freshAssetIds = candidateRows
    .map((r) => r.id as string)
    .filter((id) => !usedIds.has(id))
    .slice(0, FRESH_ASSET_LIMIT);

  // Active projects with phase inference from start_date / end_date.
  const projectRows = await sql`
    SELECT id, name, start_date, end_date
    FROM projects_v2
    WHERE site_id = ${siteId} AND status = 'active'
  `;
  const today = new Date();
  const activeProjects = projectRows.map((p) => {
    const end = p.end_date ? new Date(p.end_date as string) : null;
    const start = p.start_date ? new Date(p.start_date as string) : null;
    let phase: "beginning" | "process" | "finished" = "process";
    if (end && end < today) phase = "finished";
    else if (start && (today.getTime() - start.getTime()) < 14 * 86400_000) phase = "beginning";
    return {
      id: p.id as string,
      name: p.name as string,
      phase,
    };
  });

  // Reward prompts — read from sites.brand_dna.signals.reward_prompts.
  // Generated by lib/v2-generator/reward-prompts/generate.ts (one Haiku
  // call per site, persisted into dna JSONB).
  const [siteRow] = await sql`SELECT brand_dna FROM sites WHERE id = ${siteId}`;
  const dna = (siteRow?.brand_dna || {}) as Record<string, unknown>;
  const signals = (dna.signals as Record<string, unknown> | null) || {};
  const rawPrompts = Array.isArray(signals.reward_prompts) ? signals.reward_prompts : [];
  const prompts = rawPrompts
    .filter((p): p is Record<string, unknown> => Boolean(p) && typeof p === "object")
    .map((p) => ({
      id: String(p.id),
      label: String(p.label),
      goal: String(p.goal || "awareness"),
      intent: String(p.intent),
      framingAngle: String(p.framingAngle || ""),
      assetBias: ["proof", "process", "people", "before_after"].includes(p.assetBias as string)
        ? (p.assetBias as "proof" | "process" | "people" | "before_after")
        : undefined,
    }));

  return {
    siteId,
    pillarCoverage,
    recentArticlePillars,
    publishedCount,
    freshAssetIds,
    activeProjects,
    rewardSignals: {
      prompts,
      activeGoals: Array.from(new Set(prompts.map((p) => p.goal))),
      seasonality: null,
    },
  };
}
