export const metadata = {
  title: "Terms of Service — TracPost",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <h1>Terms of Service</h1>
      <p className="mt-2 mb-8 text-sm text-muted">Last updated: March 19, 2026</p>

      <div className="space-y-6 leading-relaxed text-foreground/80">
        <section>
          <h2 className="mb-2">1. Acceptance of Terms</h2>
          <p>
            By accessing or using TracPost (&ldquo;the Service&rdquo;), you agree to be bound
            by these Terms of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="mb-2">2. Description of Service</h2>
          <p>
            TracPost is a managed content engine that provides AI-powered social media publishing,
            blog generation, SEO optimization, and brand intelligence for businesses. The Service
            includes a web dashboard, mobile capture application (TracPost Studio), blog microsite
            hosting, and publishing to connected social media platforms.
          </p>
        </section>

        <section>
          <h2 className="mb-2">3. Subscription and Billing</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>TracPost offers paid subscription plans billed monthly via Stripe</li>
            <li>New subscribers receive a 14-day free trial with full features</li>
            <li>You may cancel your subscription at any time from the dashboard or Stripe portal</li>
            <li>Upon cancellation, your account remains accessible for 30 days (grace period)</li>
            <li>Refunds are handled per Stripe&apos;s refund policy</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2">4. Platform-Managed Social Accounts</h2>
          <p>
            As part of the managed service, TracPost may create and manage social media accounts
            on your behalf. These accounts are:
          </p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Branded with your business name and information</li>
            <li>Used exclusively for publishing your content</li>
            <li>Owned by TracPost during your active subscription</li>
            <li>Transferable to you upon request or upon cancellation</li>
            <li>Subject to each platform&apos;s terms of service</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2">5. Content Ownership</h2>
          <p>
            You retain ownership of all content you create, upload, or capture through TracPost.
            AI-generated content (blog posts, captions, hooks) is created for your exclusive use
            and you own the output. By using the Service, you grant TracPost a limited license to
            store, process, and transmit your content as necessary to provide the Service.
          </p>
        </section>

        <section>
          <h2 className="mb-2">6. AI-Generated Content</h2>
          <p>
            Content generated by TracPost&apos;s AI pipeline is provided for your use. You are
            responsible for reviewing and approving published content. TracPost does not guarantee
            the accuracy, originality, or suitability of AI-generated content. You should verify
            claims and facts before publishing, particularly in regulated industries.
          </p>
        </section>

        <section>
          <h2 className="mb-2">7. Account Responsibilities</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>You are responsible for maintaining the confidentiality of your login credentials and API keys</li>
            <li>You are responsible for all content published through your account, including AI-generated content you approve</li>
            <li>You must comply with each connected platform&apos;s terms of service and community guidelines</li>
            <li>You must not use the Service to publish illegal, harmful, or misleading content</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2">8. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Publish spam, misleading, or prohibited content</li>
            <li>Violate any applicable laws or third-party rights</li>
            <li>Attempt to access accounts or data belonging to other subscribers</li>
            <li>Interfere with the operation of the Service</li>
            <li>Resell or redistribute the Service without authorization</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2">9. Blog Microsite</h2>
          <p>
            TracPost hosts a blog microsite for each subscriber. Blog content is served via a
            TracPost subdomain or your custom domain. TracPost provides SEO optimization, RSS feeds,
            and sitemaps. You are responsible for the accuracy of published blog content.
          </p>
        </section>

        <section>
          <h2 className="mb-2">10. Data Export and Portability</h2>
          <p>
            You may export all your data (posts, media references, configuration) at any time from
            the dashboard. Upon cancellation, blog URL redirects to your new location remain active
            for 120 days to preserve SEO. Data is permanently deleted 120 days after cancellation.
          </p>
        </section>

        <section>
          <h2 className="mb-2">11. Service Availability</h2>
          <p>
            TracPost is provided &ldquo;as is&rdquo; without warranty of any kind. We do not
            guarantee uninterrupted access, successful publishing to any platform, or specific
            SEO results. Platform APIs may change, rate-limit, or revoke access at any time.
          </p>
        </section>

        <section>
          <h2 className="mb-2">12. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, TracPost shall not be liable for any
            indirect, incidental, or consequential damages arising from your use of the
            Service, including but not limited to lost revenue, failed posts, account
            suspension by third-party platforms, or SEO ranking changes.
          </p>
        </section>

        <section>
          <h2 className="mb-2">13. Termination</h2>
          <p>
            You may cancel your subscription at any time. We reserve the right to suspend or
            terminate accounts that violate these terms. Upon termination, managed social accounts
            will be transferred to you or deactivated per your preference.
          </p>
        </section>

        <section>
          <h2 className="mb-2">14. Changes to Terms</h2>
          <p>
            We may update these terms from time to time. Continued use of the Service after
            changes constitutes acceptance of the updated terms. Material changes will be
            communicated via email.
          </p>
        </section>

        <section>
          <h2 className="mb-2">15. Contact</h2>
          <p>
            For questions about these terms, contact us at{" "}
            <a href="mailto:support@tracpost.com" className="text-accent hover:underline">
              support@tracpost.com
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
