export const metadata = {
  title: "Privacy Policy — TracPost",
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <h1>Privacy Policy</h1>
      <p className="mt-2 mb-8 text-sm text-muted">Last updated: March 19, 2026</p>

      <div className="space-y-6 leading-relaxed text-foreground/80">
        <section>
          <h2 className="mb-2">1. What We Collect</h2>
          <p>When you subscribe to TracPost, we collect and store:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Your email address and account credentials (password stored as a bcrypt hash, or passwordless via magic link)</li>
            <li>Business information you provide: business name, type, location, and website URL</li>
            <li>Social media account profile information (usernames, account IDs) from connected platforms: Instagram, Facebook, TikTok, Twitter/X, YouTube, Pinterest, LinkedIn, and Google Business Profile</li>
            <li>OAuth access tokens and refresh tokens for publishing to connected platforms, encrypted at rest using AES-256-GCM</li>
            <li>Media assets you upload (photos, videos) stored on Cloudflare R2</li>
            <li>Content generated by our AI pipeline: blog posts, social captions, SEO metadata, brand playbook data</li>
            <li>Usage data: actions taken, API calls, pipeline activity logs</li>
            <li>Payment information processed by Stripe (we do not store credit card numbers)</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2">2. How We Use Your Data</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>Authenticate your identity and manage your session across web dashboard and mobile app</li>
            <li>Publish content to your connected social media accounts on your behalf</li>
            <li>Generate AI-powered content: blog posts, social captions, brand playbooks, and content strategy</li>
            <li>Host your blog microsite and serve it via your custom domain or TracPost subdomain</li>
            <li>Analyze your uploaded media using AI vision for content triage, persona detection, and quality scoring</li>
            <li>Send transactional emails: welcome messages, verification codes, pipeline notifications</li>
            <li>Monitor token expiration and automatically refresh platform credentials</li>
            <li>Display your account status, connected platforms, scheduled content, and analytics</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2">3. Platform-Managed Accounts</h2>
          <p>
            TracPost may create and manage social media accounts on your behalf as part of our
            managed service. These accounts are branded with your business information and used
            exclusively for publishing your content. You may request transfer of account ownership
            at any time. Upon cancellation, managed accounts are either transferred to you or
            deactivated per your preference.
          </p>
        </section>

        <section>
          <h2 className="mb-2">4. Data Storage and Security</h2>
          <p>
            Your data is stored in a PostgreSQL database hosted by Neon with encryption at rest
            (AES-256) and TLS in transit. OAuth tokens are encrypted at the application layer using
            AES-256-GCM before storage — they cannot be read via database access alone. Passwords
            are hashed using bcrypt and are never stored in plaintext. Media assets are stored on
            Cloudflare R2 with access controls. Payment processing is handled entirely by Stripe;
            we never see or store your credit card information.
          </p>
        </section>

        <section>
          <h2 className="mb-2">5. Third-Party Services</h2>
          <p>TracPost integrates with the following third-party services:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li><strong>Meta (Facebook/Instagram)</strong> — social media publishing via Graph API</li>
            <li><strong>TikTok</strong> — video publishing via Content Posting API</li>
            <li><strong>Twitter/X</strong> — tweet publishing via API v2</li>
            <li><strong>Google (YouTube, Business Profile)</strong> — video publishing and local business posts</li>
            <li><strong>Pinterest</strong> — pin creation via API v5</li>
            <li><strong>LinkedIn</strong> — professional content publishing via Marketing API</li>
            <li><strong>Anthropic (Claude AI)</strong> — content generation, vision analysis, brand intelligence</li>
            <li><strong>Stripe</strong> — subscription billing and payment processing</li>
            <li><strong>Cloudflare R2</strong> — media asset storage</li>
            <li><strong>Resend</strong> — transactional email delivery</li>
            <li><strong>Vercel</strong> — application hosting and blog domain provisioning</li>
          </ul>
          <p className="mt-2">
            Each platform&apos;s own privacy policy applies to data shared through their APIs.
            We do not sell, rent, or share your data with any parties beyond these service integrations.
          </p>
        </section>

        <section>
          <h2 className="mb-2">6. AI Content Generation</h2>
          <p>
            TracPost uses AI (Anthropic Claude) to generate content on your behalf. Your business
            information, uploaded media, and brand playbook data are sent to the AI API as prompts.
            Generated content (blog posts, captions, hooks) is stored in your account. We do not
            use your data to train AI models. Anthropic&apos;s data retention policies apply to API
            calls — refer to Anthropic&apos;s privacy policy for details.
          </p>
        </section>

        <section>
          <h2 className="mb-2">7. Data Retention</h2>
          <p>
            We retain your data for as long as your account is active. Upon cancellation:
          </p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Your account remains accessible for 30 days (grace period)</li>
            <li>Blog redirects to your new URL remain active for 120 days (to preserve SEO)</li>
            <li>After 120 days, all data is permanently deleted</li>
            <li>You may export all your data at any time from the dashboard</li>
          </ul>
          <p className="mt-2">
            When you disconnect a social account, we revoke the access token with the platform
            and delete the credential record from our database.
          </p>
        </section>

        <section>
          <h2 className="mb-2">8. Your Rights</h2>
          <ul className="list-disc space-y-1 pl-5">
            <li>Disconnect any social account at any time from the dashboard</li>
            <li>Export all your data (posts, media, configuration) at any time</li>
            <li>Request transfer of platform-managed social accounts</li>
            <li>Request deletion of all your data by contacting us</li>
            <li>Revoke TracPost&apos;s access via each platform&apos;s app settings</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2">9. Data Deletion</h2>
          <p>
            To request deletion of your data, visit our{" "}
            <a href="/data-deletion" className="text-accent hover:underline">
              data deletion page
            </a>{" "}
            or contact us at the email below. We will process deletion requests within 30 days.
          </p>
        </section>

        <section>
          <h2 className="mb-2">10. Contact</h2>
          <p>
            For privacy inquiries, contact us at{" "}
            <a href="mailto:privacy@tracpost.com" className="text-accent hover:underline">
              privacy@tracpost.com
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
